apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-lzpw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-htme-tenant/rhtap-demo-app/hacbs-test-project-lzpw@sha256:4a4b5a063b1496c6dea10d4b45ae06c3b355af15f8ef30ad23b7d9e02adef91c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
